name: Download Assets
on: [workflow_dispatch]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download audio
        run: |
          mkdir -p public
          curl -L "https://drive.google.com/uc?export=download&id=1L39yx0sNJi3X-eE1KiR6OnXuB6nYNQVz" -o public/audio.mp3
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add audio.mp3 from Google Drive
          file_pattern: public/audio.mp3
